sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: UtyUAkz30lvZ6F7+57kDjNFgqSo2Mm1kT5mWgj0u0F4LWwNYehk3RJSYUznZhR+4fyAimqXA0d+AO/FSj5hx8egg1wFet6MXPlEPqm4GYGbCLLCwmNqVdMNfnM98ItHOK9qeWxWBx/Ik5PBh+d0DKxWZOliUASoCM6CGj2XMJj7xRbYHSiz+2GBeoc7ejtT1Jh11C0Jyt3jdnVoufuEUT3JSQJ8efrUA8a9h8j0GZ96BQC9MltDuRSCimMpqpNxed4RchkLeVzbdqK2v5WG4L1Ughq/u340z2RILlolRFRu16jwqSfR1JgHkd4pNq24r3sWfpOA6XKdob/mhQCIEfDruVq5Av/66Exv9K/axXxg4/Ete76i4iSxIrHbTu4Yy3gZFb3qEtzm9no5uALOfyJJt2nnpKogMrzstrtNohsJhICslj//aa3B6dmXFxY0mNhnATwNAe+F3tlyM3qk+9LM9Gg7R6DEQczj4ij14nlAlj1eK+8wCJuoDFmAcxPPi43s8P8m5Vyystkqdp0sf/DLTigFXjruiEYFMtquLtsPqfakZ+tOppa39gq2VveghWvDQS6zNZFqhP/kIgBnJAmYGxMxW9nYgf6ZVShecUeo9PUSD+DePOPEcfEqntdqIDWaC7Aa+B/Jlg+RINy4zLnAXzUEJEMwPHPZXRntn9CU=
branches:
  only:
  - master
